/ic120/global_costmap:
  global_costmap:
    ros__parameters:
      #Costmap2D paraneters
      always_send_full_costmap: True
      footprint_padding: 0.5
      footprint: "[[3.025, -1.685], [-3.025, -1.685], [-3.025, 1.685], [3.025, 1.685]]"
      global_frame: /ic120_tf/map
      height: 100.0
      width: 100.0
      observation_sources: scan
      origin_x: -20.0
      origin_y: -20.0
      publish_frequency: 5.0
      resolution: 0.1
      robot_base_frame: /ic120_tf/base_link
      rolling_window: false
      transform_tolerance: 0.5
      update_frequency: 5.0
      plugins: ["obstacle_layer", "voxel_layer", "inflation_layer"]
      
      # Obstacle Layer parameters
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: front/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
        sensor_frame: front_laser
      
      # Voxel Layer parameters
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        publish_voxel_map: false
        origin_z: 0.0
        z_resolution: 1
        z_voxels: 2
      
      # Infration Layer parameters
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.30

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True