/ic120/local_costmap:
  local_costmap:
    ros__parameters:
      #Costmap2D paraneters
      always_send_full_costmap: True
      footprint_padding: 0.5
      footprint: "[[3.025, -1.685], [-3.025, -1.685], [-3.025, 1.685], [3.025, 1.685]]"
      global_frame: /ic120_tf/odom
      height: 20.0
      width: 20.0
      observation_sources: scan
      publish_frequency: 10.0
      resolution: 0.05
      robot_base_frame: /ic120_tf/base_link
      rolling_window: true
      transform_tolerance: 0.5
      update_frequency: 10.0
      plugins: ["obstacle_layer", "voxel_layer", "inflation_layer"]
      
      # Obstacle Layer parameters
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: front/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
        sensor_frame: front_laser
      
      # Voxel Layer parameters
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        publish_voxel_map: false
        origin_z: 0.0
        z_resolution: 1
        z_voxels: 2
      
      # Infration Layer parameters
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.30