bt_navigator:
  ros__parameters:
    global_frame: /ic120/map
    robot_base_frame: /ic120/base_link/pose
    odom_topic: /ic120/odom
    bt_loop_duration: 10
    default_server_timeout: 20
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator/NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator/NavigateThroughPosesNavigator"
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_are_error_codes_active_condition_bt_node
      - nav2_would_a_controller_recovery_help_condition_bt_node
      - nav2_would_a_planner_recovery_help_condition_bt_node
      - nav2_would_a_smoother_recovery_help_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_nodeCouldn't load critics! Caught exception: No critics defined for FollowPath
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node
      - nav2_is_battery_charging_condition_bt_node
    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

################################
#base_local_planner_params.yaml#
################################map

controller_server:
  ros__parameters:
    base_local_planner:
    ros__parameters:
      controller_frequency: 5.0
      min_x_velocity_threshold: 0.001
      min_y_velocity_threshold: 0.5
      min_theta_velocity_threshold: 0.1
      failure_tolerance: 0.3
      progress_checker_plugins: ["progress_checker"]
      goal_checker_plugins: ["goal_checker"]
      controller_plugins: ["FollowPath"]

      #progress cehcker parameters
      progress_checker:
        plugin: "nav2_controller::SimpleProgressChecker"
        required_movement_radius: 0.5
        movement_time_allowance: 10.0
          
      #goal_checker_plugins
      goal_checker:
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 1.0
        yaw_goal_tolerance: 0.1
        stateful: True
        
      #DWB parameters
      FollowPath:
        plugin: "dwb_core::DWBLocalPlanner"
        # dwb controller parameters
        critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
        prune_plan: True
        debug_trajectory_details: True
        transform_tolerance: 0.2
        short_circuit_trajectory_evaluation: True
        path_distance_bias: 0.5
        goal_distance_bias: 0.8
        occdist_scale: 0.03
        max_scaling_factor: 0.2
        scaling_speed: 0.25
        PathAlign.scale: 32.0
        GoalAlign.scale: 24.0
        PathDist.scale: 32.0
        GoalDist.scale: 24.0
        
        #XY Theta Iterator parameters
        vx_samples: 5
        vy_samples: 5
        vth_samples: 25
        
        #Kinematic parameters parameters
        max_vel_theta : 1.5
        min_speed_xy: 0.0
        max_speed_xy: 0.0
        min_speed_theta: 0.0
        min_vel_x: -1.0
        min_vel_y: 0.0
        max_vel_x: 1.0
        max_vel_y: 0.0
        acc_lim_x: 3.0
        acc_lim_y: 0.0
        acc_lim_theta: 3.1
        decel_lim_x: 0.0
        decel_lim_y: 0.0
        decel_lim_theta: 0.0
          
        # StandardTrajectoryGenerator parameters
        sim_time: 4.0
        time_granularity: 0.02s
        angular_granularity: 0.02
        
        # GoalAlignClitic parameters
        forward_point_distance: 0.6
        
        # OscillationCritidc parametersodom
        oscillation_reset_dist: 0.0
        oscillation_rest_angle: 0.0

###########################
#local_costmap_params.yaml#
###########################

local_costmap:
  local_costmap:
    ros__parameters:
      #Costmap2D paraneters
      always_send_full_costmap: True
      footprint_padding: 0.5
      footprint: "[[3.025, -1.685], [-3.025, -1.685], [-3.025, 1.685], [3.025, 1.685]]"
      global_frame: /ic120/odom
      height: 20.0
      width: 20.0
      observation_sources: scan
      publish_frequency: 10.0
      resolution: 0.05
      robot_base_frame: /ic120/base_link/pose
      rolling_window: true
      transform_tolerance: 0.5
      update_frequency: 10.0
      plugins: ["obstacle_layer", "voxel_layer", "inflation_layer"]
      
      # Obstacle Layer parameters
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: front/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
        sensor_frame: front_laser
      
      # Voxel Layer parameters
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        publish_voxel_map: false
        origin_z: 0.0
        z_resolution: 1
        z_voxels: 2
      map
      # Infration Layer parameters
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.30

############################
#global_costmap_params.yaml#
############################

global_costmap:
  global_costmap:
    ros__parameters:
      #Costmap2D paraneters
      always_send_full_costmap: True
      footprint_padding: 0.5
      footprint: "[[3.025, -1.685], [-3.025, -1.685], [-3.025, 1.685], [3.025, 1.685]]"
      global_frame: /ic120/map
      height: 100.0
      width: 100.0
      observation_sources: scan
      origin_x: -20.0
      origin_y: -20.0
      publish_frequency: 5.0
      resolution: 0.1
      robot_base_frame: /ic120/base_link/pose
      rolling_window: false
      transform_tolerance: 0.5
      update_frequency: 5.0
      plugins: ["obstacle_layer", "voxel_layer", "inflation_layer"]
      
      # Obstacle Layer parameters
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: front/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
        sensor_frame: front_laser
      
      # Voxel Layer parameters
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        publish_voxel_map: false
        origin_z: 0.0
        z_resolution: 1
        z_voxels: 2
      
      # Infration Layer parameters
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.30

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

#################################
#base_global_planner_params.yaml#
#################################

planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    local_frame: /ic120/odom
    global_frame: /ic120/map
    robot_base_frame: /ic120/base_link/pose
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.26, 0.0, 1.0]
    min_velocity: [-0.26, 0.0, -1.0]
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0